"use client";

import { useEffect, useState } from "react";
import {
  subscribeUserToPushAction,
  unsubscribeUserFromPushAction,
  sendSelfTestPushAction,
  getVapidPublicKeyAction,
} from "@/app/(portal)/profile/push-actions";

function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

type ButtonVariant = "pill" | "banner" | "full" | "dropdown-item";

export function EnableNotificationsButton({
  variant = "pill",
  className = "",
}: {
  variant?: ButtonVariant;
  className?: string;
}) {
  const [isSupported, setIsSupported] = useState<boolean>(false);
  const [permission, setPermission] = useState<NotificationPermission>("default");
  const [isSubscribed, setIsSubscribed] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isSendingTest, setIsSendingTest] = useState<boolean>(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  useEffect(() => {
    let isMounted = true;
    async function init() {
      if (typeof window !== "undefined" && "serviceWorker" in navigator && "PushManager" in window && "Notification" in window) {
        if (!isMounted) return;
        setIsSupported(true);
        setPermission(Notification.permission);
        try {
          const registration = await navigator.serviceWorker.register("/sw.js", { scope: "/" });
          await navigator.serviceWorker.ready;
          const subscription = await registration.pushManager.getSubscription();
          if (isMounted) {
            setIsSubscribed(!!subscription);
          }
        } catch (err: unknown) {
          console.warn("Could not check push subscription:", err);
        } finally {
          if (isMounted) {
            setIsLoading(false);
          }
        }
      } else {
        if (isMounted) {
          setIsSupported(false);
          setIsLoading(false);
        }
      }
    }
    init();
    return () => {
      isMounted = false;
    };
  }, []);

  async function handleEnablePush() {
    setIsLoading(true);
    setStatusMessage(null);

    try {
      if (!isSupported) {
        alert("Push notifications are not supported in this browser.");
        return;
      }

      // 1. Request permission
      const requestedPermission = await Notification.requestPermission();
      setPermission(requestedPermission);

      if (requestedPermission === "denied") {
        setStatusMessage("Notifications blocked. Please allow notifications in your browser settings.");
        return;
      }

      if (requestedPermission !== "granted") {
        return;
      }

      // 2. Register / retrieve service worker
      const registration = await navigator.serviceWorker.register("/sw.js", { scope: "/" });
      await navigator.serviceWorker.ready;

      // 3. Get VAPID public key (client env or server action fallback)
      let vapidPublicKey: string | null | undefined = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
      if (!vapidPublicKey) {
        vapidPublicKey = await getVapidPublicKeyAction();
      }

      if (!vapidPublicKey) {
        throw new Error("VAPID Public Key is missing on the server. Please check your Vercel Environment Variables.");
      }

      // 4. Subscribe to PushManager
      const convertedKey = urlBase64ToUint8Array(vapidPublicKey);
      let subscription = await registration.pushManager.getSubscription();

      if (!subscription) {
        subscription = await registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: convertedKey,
        });
      }

      // 5. Store subscription on database
      const jsonSubscription = subscription.toJSON();
      if (!jsonSubscription.endpoint || !jsonSubscription.keys?.p256dh || !jsonSubscription.keys?.auth) {
        throw new Error("Invalid push subscription format generated by browser.");
      }

      await subscribeUserToPushAction({
        endpoint: jsonSubscription.endpoint,
        keys: {
          p256dh: jsonSubscription.keys.p256dh,
          auth: jsonSubscription.keys.auth,
        },
      });

      setIsSubscribed(true);
      setStatusMessage("Notifications successfully enabled!");

      // 6. Automatically trigger an initial test notification so the user sees real notification
      await sendSelfTestPushAction().catch(() => {});
    } catch (error: unknown) {
      const errorMsg = error instanceof Error ? error.message : "Please check browser permissions.";
      console.error("Failed to enable push notifications:", error);
      setStatusMessage("Failed to enable notifications: " + errorMsg);
    } finally {
      setIsLoading(false);
    }
  }

  async function handleDisablePush() {
    setIsLoading(true);
    setStatusMessage(null);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await subscription.unsubscribe();
        await unsubscribeUserFromPushAction(subscription.endpoint);
      }
      setIsSubscribed(false);
      setStatusMessage("Notifications disabled on this device.");
    } catch (error: unknown) {
      const errorMsg = error instanceof Error ? error.message : "Error disabling notifications";
      console.error("Failed to disable push notifications:", error);
      setStatusMessage(errorMsg);
    } finally {
      setIsLoading(false);
    }
  }

  async function handleSendTest() {
    setIsSendingTest(true);
    setStatusMessage(null);
    try {
      const res = await sendSelfTestPushAction();
      if (res?.success) {
        setStatusMessage("Test push notification sent! Check your notification tray.");
      } else {
        setStatusMessage("Failed to send test push: " + (res?.error || ""));
      }
    } catch (err: unknown) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      console.error("Error sending test push:", err);
      setStatusMessage("Error: " + errorMsg);
    } finally {
      setIsSendingTest(false);
    }
  }

  if (!isSupported) {
    if (variant === "full") {
      return (
        <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-300">
          Push notifications are not supported on this browser/environment. If you are using iOS Safari, add this web app to your Home Screen first.
        </div>
      );
    }
    return null;
  }

  // Variant: TopNav Pill button
  if (variant === "pill") {
    if (permission === "denied") {
      return null;
    }

    if (isSubscribed) {
      return null; // Already enabled, keep topnav clean
    }

    return (
      <button
        onClick={handleEnablePush}
        disabled={isLoading}
        className={`inline-flex items-center gap-1.5 px-3 py-1 text-xs font-medium rounded-full bg-accent/15 text-accent hover:bg-accent/25 border border-accent/30 transition-all duration-200 shadow-sm animate-pulse hover:animate-none ${className}`}
        title="Click to receive instant phone & desktop updates"
      >
        <span className="text-sm">🔔</span>
        <span>{isLoading ? "Enabling..." : "Enable Notifications"}</span>
      </button>
    );
  }

  // Variant: Dropdown item inside Notification Bell
  if (variant === "dropdown-item") {
    if (isSubscribed) {
      return (
        <div className="px-4 py-2.5 bg-white/5 border-b border-white/5 flex items-center justify-between text-xs">
          <span className="text-emerald-400 flex items-center gap-1.5 font-medium">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
            Push Active
          </span>
          <button
            onClick={handleSendTest}
            disabled={isSendingTest}
            className="text-[11px] text-white/60 hover:text-white underline transition-colors"
          >
            {isSendingTest ? "Sending..." : "Test Push 🚀"}
          </button>
        </div>
      );
    }

    if (permission === "denied") {
      return (
        <div className="px-4 py-2 bg-rose-500/10 border-b border-rose-500/20 text-[11px] text-rose-300 flex items-center justify-between">
          <span>Push notifications blocked in browser</span>
        </div>
      );
    }

    return (
      <div className="p-3 bg-accent/10 border-b border-accent/20 flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-white/90">Get Real-Time Alerts</p>
            <p className="text-[11px] text-white/60">Receive updates even when closed</p>
          </div>
          <button
            onClick={handleEnablePush}
            disabled={isLoading}
            className="px-2.5 py-1 text-xs font-medium rounded-md bg-accent text-white hover:bg-accent/80 transition-colors shrink-0 shadow"
          >
            {isLoading ? "Enabling..." : "Enable Notifications 🔔"}
          </button>
        </div>
      </div>
    );
  }

  // Variant: Full settings card (for profile / settings page)
  return (
    <div className={`space-y-3 ${className}`}>
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl bg-white/5 border border-white/10">
        <div>
          <div className="flex items-center gap-2">
            <h4 className="text-sm font-semibold text-white">Browser Push Notifications</h4>
            {isSubscribed ? (
              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-medium bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                Active ✅
              </span>
            ) : permission === "denied" ? (
              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-medium bg-rose-500/20 text-rose-300 border border-rose-500/30">
                Blocked 🚫
              </span>
            ) : (
              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-medium bg-amber-500/20 text-amber-300 border border-amber-500/30">
                Not Enabled
              </span>
            )}
          </div>
          <p className="text-xs text-white/60 mt-1">
            Receive native system push notifications on your phone or desktop for assignments, coverages, and society announcements.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {isSubscribed ? (
            <>
              <button
                onClick={handleSendTest}
                disabled={isSendingTest}
                className="px-3 py-1.5 text-xs font-medium rounded-lg bg-white/10 hover:bg-white/15 text-white border border-white/10 transition-colors"
              >
                {isSendingTest ? "Sending..." : "Send Test 🚀"}
              </button>
              <button
                onClick={handleDisablePush}
                disabled={isLoading}
                className="px-3 py-1.5 text-xs font-medium rounded-lg bg-rose-500/20 hover:bg-rose-500/30 text-rose-300 border border-rose-500/30 transition-colors"
              >
                {isLoading ? "Updating..." : "Disable"}
              </button>
            </>
          ) : (
            <button
              onClick={handleEnablePush}
              disabled={isLoading}
              className="px-4 py-2 text-xs font-semibold rounded-lg bg-accent hover:bg-accent/80 text-white shadow-lg shadow-accent/20 transition-all flex items-center gap-1.5"
            >
              <span>🔔</span>
              <span>{isLoading ? "Enabling..." : "Enable Notifications 🔔"}</span>
            </button>
          )}
        </div>
      </div>

      {statusMessage && (
        <p className="text-xs text-accent/90 px-1">{statusMessage}</p>
      )}

      {permission === "denied" && (
        <div className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/20 text-xs text-rose-300">
          <strong>Notifications are blocked:</strong> To enable push alerts, click the lock/settings icon in your browser&apos;s address bar and set Notifications to &quot;Allow&quot;.
        </div>
      )}
    </div>
  );
}
